language: node_js
node_js:
  - "12"
  - "node"
cache:
  yarn: true
  directories:
    - .cache
    - node_modules
install:
  - npm install
script:
  - npm run build --prefix-paths
  on:
    branch: master